name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1' # latest 1.x stable release
          - '1.8'
          #- 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - name: Merge master -> gh-pages
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'gh-pages'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
      - uses: actions/upload-artifact@v2
          with:
            name: lcov
            path: lcov.info
        
  process_cov_info:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: lcov
          path: docs/coverage/
      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v1
        with:
              dotnet-version: 3.1.302
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.6.4
        with:
            reports: 'docs/coverage/lcov.info' # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
            targetdir: 'docs/coverage' # REQUIRED # The directory where the generated report should be saved.
            historydir: 'docs/coverage/history' # Optional directory for storing persistent coverage information. Can be used in future reports to show coverage evolution.
            reporttypes: 'HtmlInline;Badges' # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
            verbosity: 'Info' # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
            tag: '${{ github.run_number }}_${{ github.run_id }}' # Optional tag or build version.

      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          add: 'docs/*'
          message: 'Coverage Report ${{ github.sha }}'
          ref: 'gh-pages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
